services:
  
  forum_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum_app
    ports:
      - "8000:8000"    # Main Forum Application
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      # - ./logs:/app/logs
    networks:
      - ai_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    # Добавляем extra_hosts для Linux систем
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ai_network
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: python -m celery -A app.ai_manager.forum_manager worker -l info
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    networks:
      - ai_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ollama_models:
    driver: local
  # ai_manager_logs:
  #   driver: local

networks:
  ai_network:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.20.0.0/16
