FROM postgres:15-alpine

# Устанавливаем переменные окружения для PostgreSQL
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Копируем скрипт инициализации базы данных
COPY docker/init-db.sql /docker-entrypoint-initdb.d/

# Открываем порт
EXPOSE 5432

# Добавляем healthcheck
HEALTHCHECK --interval=10s --timeout=3s --start-period=30s --retries=3 \
  CMD pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
