"""Alter context table

Revision ID: 5fc867fd5592
Revises: 79d561dfb7bc
Create Date: 2025-07-21 08:23:48.149938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc867fd5592'
down_revision: Union[str, Sequence[str], None] = '79d561dfb7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_base_context', sa.Column('reply_name', sa.Text(), nullable=True))
    op.add_column('users_base_context', sa.Column('topic', sa.Text(), nullable=True))
    op.drop_constraint(op.f('users_base_context_topic_id_fkey'), 'users_base_context', type_='foreignkey')
    op.drop_constraint(op.f('users_base_context_reply_to_fkey'), 'users_base_context', type_='foreignkey')
    op.drop_constraint(op.f('users_base_context_user_id_fkey'), 'users_base_context', type_='foreignkey')
    op.drop_column('users_base_context', 'user_id')
    op.drop_column('users_base_context', 'reply_to')
    op.drop_column('users_base_context', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_base_context', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users_base_context', sa.Column('reply_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users_base_context', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_base_context_user_id_fkey'), 'users_base_context', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('users_base_context_reply_to_fkey'), 'users_base_context', 'messages', ['reply_to'], ['id'])
    op.create_foreign_key(op.f('users_base_context_topic_id_fkey'), 'users_base_context', 'topics', ['topic_id'], ['id'])
    op.drop_column('users_base_context', 'topic')
    op.drop_column('users_base_context', 'reply_name')
    # ### end Alembic commands ###
