"""Create context table

Revision ID: 79d561dfb7bc
Revises: 961b1c95931c
Create Date: 2025-07-20 14:45:35.375620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79d561dfb7bc'
down_revision: Union[str, Sequence[str], None] = '961b1c95931c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_context')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_context',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('character_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reply_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reply_to'], ['messages.id'], name=op.f('users_context_reply_to_fkey')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('users_context_topic_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_context_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_context_pkey'))
    )
    # ### end Alembic commands ###
